apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-frontend
  labels:
    app: Aaryaman-Task-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: frontend-frontend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
