apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-backend
  labels:
    app: Aaryman-Task-3
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: backend-backend:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
