apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000        # the port where the service is hosted to 
      targetPort: 5000  # the port where thhe service is hosted from present in the conatiner 
  type: NodePort
