version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      network: host   # Use the host network during build
    network_mode: host  # Use host networking at runtime as well
    # (Note: If you're using host networking, you may not need to map ports)
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://user:password@db:3306/your_database
    volumes:
      - .:/app
    restart: always
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: your_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always

volumes:
  db_data:
